model:
  name: /sda/llm_weights/Qwen2.5-7B-Instruct
  revision: a09a35458c702b33eeacc393d103063234e8bc28
  cache_dir: null
  num_hidden_layers: 28
  dtype: bfloat16
  device_map: auto
  attention_implementation: sdpa
  trust_remote_code: false
  use_cache: true
  max_new_tokens: 2048
  do_sample: false
